spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/iceberg?characterEncoding=utf-8&serverTimezone=UTC&AllowPublicKeyRetrieval=True&useSSL=false
    url: jdbc:mysql://database4156.c45jfzqe0ovx.us-east-1.rds.amazonaws.com:3306/iceberg?characterEncoding=utf-8&serverTimezone=UTC&AllowPublicKeyRetrieval=True&useSSL=false
    username: dbuser
    password: dbuserdbuser
  jpa:
    database: mysql
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.iceberg.entity

logging:
  level:
    root: info
    org:
      springframework:
        web: debug
    com.iceberg.dao: debug
