spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iceberg?characterEncoding=utf-8&serverTimezone=UTC&AllowPublicKeyRetrieval=True&useSSL=false
    username: dbuser
    password: dbuserdbuser
  jpa:
    database: mysql
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: iceberg4156@gmail.com
    password: ase4156iceberg.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.iceberg.entity

logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
    com.iceberg.dao: debug
