name: "CheckStyle"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          filter_mode: "nofilter"
          tool_name: 'reviewdog'