# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  run: mvn -B package --file pom.xml -Dmaven.test.skip=true
        run: |
          mvn -B package --file pom.xml
          bash <(curl -s https://codecov.io/bash)
      - name: Generate Report
        run: |
          mvn site
          cp -r target/site/* report/
          git add report/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          git commit -m "[ADD] Report From CI" -a
      - name: Push changes
        if: ${{ github.event_name == 'pull_request' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #        branch: config/report
          branch: ${{ github.head_ref }}
          force: true
      - name: Push changes
        if: ${{ github.event_name == 'push' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #        branch: config/report
          branch: ${{ github.ref }}
          force: true

